services:
  houxhandyman-wp:
    image: wp-cubix
    container_name: houxhandyman-wp
    ports:
      - 80:81
      - 443:443
    volumes:
      - ./volumes/uploads:/opt/wp-content/uploads
      - ./volumes/composer.json:/var/www/html/composer.json
    environment:
      WP_DOMAIN: yourdomain
      WP_UPLOADS_EXTERNAL_DIR: "/opt/wp-content/uploads" 
      WP_CONFIG_EXTRA_PHP: "define('HOUX_EXTRA_PHP_TEST', 'SOME VALUE');"
      WP_DB_NAME: yourdbname
      WP_DB_USER: yourdbuser
      WP_DB_PASS: yourdbpwd
      WP_DB_HOST: wp-mariadb
      WP_DB_HOST: wp-mariadb
    networks:
      - wp-cubix-network

networks:
  wp-cubix-network:
    external: true