services:
  wp-mariadb:
    image: mariadb:11.3.2-jammy
    container_name: wp-mariadb
    volumes:
      - ./volumes/mariadb-data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: audaciousduck7
    networks:
      wp-cubix-network:
        aliases:
          - wp-mariadb

networks:
  wp-cubix-network:
    external: true